import type {
  PhilosophyPrinciple,
  NiwakiStyle,
  PruningTechnique,
  TrainingMethod,
  WireType,
  Species,
  Tool,
  SeasonalTask,
  CommonMistake,
  YearOnePlan,
  Resources,
} from '@/types/techniques';

export const PHILOSOPHY_PRINCIPLES: PhilosophyPrinciple[] = [
  {
    principle: 'Asymmetry',
    japanese: '不均衡',
    romanji: 'Fukinkou',
    meaning: 'Perfect symmetry reads as artificial; celebrate imbalance',
  },
  {
    principle: 'Negative Space',
    japanese: '間',
    romanji: 'Ma',
    meaning: 'Gaps between clouds are as important as foliage itself',
  },
  {
    principle: 'Suggestion of Age',
    japanese: '古さ',
    romanji: 'Furusa',
    meaning: 'Broad trunks, gnarled branches suggest decades of growth',
  },
  {
    principle: 'Natural Movement',
    japanese: '動き',
    romanji: 'Ugoki',
    meaning: 'Branches appear shaped by wind, weather, and time',
  },
];

export const NIWAKI_STYLES: NiwakiStyle[] = [
  {
    id: 'chokkan',
    name: 'Chokkan',
    japaneseName: 'Formal Upright',
    japaneseCharacters: '直幹',
    difficulty: 3,
    description:
      'A perfectly straight trunk tapering from base to apex with symmetrically arranged horizontal branches. Represents trees growing in ideal conditions.',
    characteristics: [
      'Trunk: Perfectly vertical',
      'Branch arrangement: Symmetrical, alternating',
      'Apex: Directly above base',
    ],
    bestSpecies: ['Pines', 'Japanese cedar'],
  },
  {
    id: 'moyogi',
    name: 'Moyogi',
    japaneseName: 'Informal Upright',
    japaneseCharacters: '模様木',
    difficulty: 2,
    description:
      'The most frequently used style. Gently curved trunk with irregular, natural-looking branch placement.',
    characteristics: [
      'Trunk: S-curves, organic movement',
      'Branch arrangement: Asymmetrical, natural',
      'Apex: Roughly aligned with base',
    ],
    bestSpecies: ['Most species', 'Excellent for beginners'],
  },
  {
    id: 'shakan',
    name: 'Shakan',
    japaneseName: 'Slanting',
    japaneseCharacters: '斜幹',
    difficulty: 3,
    description:
      'Trunk positioned at 30-80 degrees from vertical, with asymmetric branch balance.',
    characteristics: [
      'Trunk: 30-80° from vertical',
      'Root system: More prominent on one side',
      'Branch arrangement: Counterweights the lean',
    ],
    bestSpecies: ['Junipers', 'Pines'],
  },
  {
    id: 'fukinagashi',
    name: 'Fukinagashi',
    japaneseName: 'Windswept',
    japaneseCharacters: '吹き流し',
    difficulty: 5,
    description:
      'The most dramatic style. All branches and foliage swept in one predominant direction.',
    characteristics: [
      'Trunk: Strong slant, often twisted',
      'Branch arrangement: All in one direction',
      'Effect: Coastal/mountain wind exposure',
    ],
    bestSpecies: ['Pines', 'Junipers', 'Hawthorn'],
  },
  {
    id: 'kengai',
    name: 'Kengai',
    japaneseName: 'Cascade',
    japaneseCharacters: '懸崖',
    difficulty: 4,
    description:
      'Trunk rises then bends dramatically downward, representing cliff-growing trees.',
    characteristics: [
      'Trunk: Falls below ground level',
      'Branch arrangement: Follows cascade direction',
      'Effect: Waterfall, cliff-edge drama',
    ],
    bestSpecies: ['Junipers', 'Cotoneaster', 'Willows'],
  },
  {
    id: 'han-kengai',
    name: 'Han-Kengai',
    japaneseName: 'Semi-Cascade',
    japaneseCharacters: '半懸崖',
    difficulty: 3,
    description:
      'Similar to cascade but branches stay above the base level.',
    characteristics: [
      'Trunk: Horizontal to slightly downward',
      'Less extreme than full cascade',
      'Effect: Tree over water',
    ],
    bestSpecies: ['Junipers', 'Cotoneaster', 'Willows'],
  },
  {
    id: 'kabudachi',
    name: 'Kabudachi',
    japaneseName: 'Multi-Trunk Clump',
    japaneseCharacters: '株立ち',
    difficulty: 4,
    description:
      'Multiple trunks from single root system. Traditional configurations: two (sokan), three (sankan), or five+ trunks. Never four (shi sounds like death).',
    characteristics: [
      'Trunks: Varying diameters',
      'Three-trunk: "Father, mother, son"',
      'Odd numbers preferred',
    ],
    bestSpecies: ['Maples', 'Elms', 'Zelkova'],
  },
];

export const PRUNING_TECHNIQUES: PruningTechnique[] = [
  {
    id: 'sukashi',
    name: 'Sukashi',
    japaneseName: 'Thinning Cuts',
    japaneseCharacters: '透かし',
    purpose: 'Remove selected branches to allow light/air penetration and reveal structure.',
    difficulty: 3,
    timing: ['Late winter (deciduous)', 'Late spring (evergreens)'],
    seasons: ['winter', 'spring'],
    categories: ['structural'],
    process: [
      { step: 1, description: 'Work from TOP of tree downward' },
      { step: 2, description: 'Remove all dead wood first' },
      { step: 3, description: 'Remove karami eda (intertwined branches)' },
      { step: 4, description: 'Remove tachi eda (branches pointing directly up/down)' },
      { step: 5, description: 'Remove crowding branches growing toward centre' },
      { step: 6, description: 'Reduce each fork to just two branches (Y-shaped architecture)' },
    ],
    bestFor: ['All species', 'Structural work'],
    tips: ['The "Rule of Two": At every fork with three or more branches, keep only two'],
    science: 'Thinning allows light to penetrate the canopy, stimulating interior bud development. Without adequate light, inner branches weaken and eventually die back, leaving only peripheral growth.',
    criticalWindow: null,
    goalVisual: 'transparent-clouds',
  },
  {
    id: 'midoritsumi',
    name: 'Midoritsumi',
    japaneseName: 'Pine Candle Pinching',
    japaneseCharacters: '緑摘み',
    purpose: 'Control pine growth and encourage density.',
    difficulty: 4,
    timing: ['Late spring when candles are tender enough to snap — before needles form'],
    seasons: ['spring'],
    categories: ['pine-specific'],
    process: [
      { step: 1, description: 'Identify candle structure at each branch tip' },
      { step: 2, description: 'Locate dominant central candle + smaller secondary candles' },
      { step: 3, description: 'Snap out central candle completely' },
      { step: 4, description: 'Reduce secondary candles: vigorous areas 1/2 to 2/3, weak areas no more than 1/3' },
      { step: 5, description: 'Start with WEAKER areas first, finish strongest areas 2-3 weeks later' },
    ],
    warnings: [
      'Never use scissors — snapping produces better results',
      'Missing the timing window means candles must be cut, producing inferior results',
    ],
    bestFor: ['Japanese Black Pine', 'Japanese White Pine', 'Scots Pine'],
    tips: ['Energy balancing: starting with weak areas redistributes energy throughout the tree'],
    science: 'Removing the dominant central candle eliminates apical dominance, forcing the tree to redirect growth hormones (auxins) to secondary buds. This creates multiple smaller shoots instead of one strong leader, resulting in denser foliage pads.',
    criticalWindow: '2-3 weeks in late spring',
    goalVisual: 'candle-pinching',
  },
  {
    id: 'momiage',
    name: 'Momiage',
    japaneseName: 'Needle Plucking',
    japaneseCharacters: '揉み上げ',
    purpose: 'Remove old needles to reveal limb structure and maintain health.',
    difficulty: 3,
    timing: ['Late autumn (November-December in temperate climates)'],
    seasons: ['autumn'],
    categories: ['pine-specific', 'maintenance'],
    process: [
      { step: 1, description: 'Target two-year-old needles only' },
      { step: 2, description: 'Leave current-year needles intact' },
      { step: 3, description: 'Pull downward with thumb and fingers' },
      { step: 4, description: 'Kyoto style: Leave 15 pairs of needles' },
      { step: 5, description: 'Other regions: Leave 7-8 pairs' },
    ],
    bestFor: ['All pine species'],
    tips: [
      'Reveals graceful branch architecture',
      'Allows light to reach inner branches',
      'Creates characteristic sparse elegance',
    ],
    science: 'Old needles naturally yellow and drop, but removing them proactively allows light to reach interior buds before they go dormant. This maintains back-budding potential and prevents the "lions tail" effect where foliage only exists at branch tips.',
    criticalWindow: null,
    goalVisual: 'needle-plucking',
  },
  {
    id: 'pinching',
    name: 'Pinching',
    japaneseName: 'Soft Growth Control',
    japaneseCharacters: '摘芯',
    purpose: 'Control direction and encourage density on broadleaf species.',
    difficulty: 2,
    timing: ['Throughout growing season as new growth emerges'],
    seasons: ['spring', 'summer'],
    categories: ['deciduous', 'maintenance'],
    process: [
      { step: 1, description: 'Remove soft emerging growth before it hardens' },
      { step: 2, description: 'Use thumb and forefinger (not tools)' },
      { step: 3, description: 'Pinch to desired length/direction' },
    ],
    warnings: ['Never prune into old wood on conifers — they cannot regenerate from bare branches'],
    bestFor: ['Broadleaf species', 'Deciduous trees'],
    tips: ['Removes apical auxin (growth hormone at shoot tips), redirecting energy to interior buds'],
    science: 'Auxin hormones concentrate at shoot tips, suppressing lateral bud development. Removing the tip eliminates this hormonal signal, allowing dormant lateral buds to activate. The result is two or more shoots where there was one.',
    criticalWindow: null,
    goalVisual: 'pinching',
  },
  {
    id: 'defoliation',
    name: 'Partial Defoliation',
    japaneseName: 'Leaf Reduction',
    japaneseCharacters: '葉刈り',
    purpose: 'Dramatically increase ramification (fine branching) on deciduous species.',
    difficulty: 4,
    timing: ['Midsummer'],
    seasons: ['summer'],
    categories: ['deciduous'],
    process: [
      { step: 1, description: 'Remove leaves throughout the tree' },
      { step: 2, description: 'Leave ONE small leaf at each branch tip (the "sap drawer")' },
      { step: 3, description: 'Wait for new shoots with multiple leaves to replace removed leaves' },
    ],
    bestFor: ['Hornbeam', 'Oak', 'Beech', 'Maples'],
    science: 'Leaves produce sugars through photosynthesis and regulate water flow. Removing them triggers the tree to produce a second flush of growth with smaller leaves and additional branching points. The "sap drawer" leaf maintains transpiration to keep the branch alive.',
    criticalWindow: 'Midsummer only — tree needs time to recover before dormancy',
    goalVisual: 'defoliation',
  },
];

export const TRAINING_METHODS: TrainingMethod[] = [
  {
    id: 'guy-wiring',
    name: 'Guy Wiring',
    description: 'The preferred method for garden-scale niwaki. Uses anchor points to pull branches into position with gentle, consistent pressure over time.',
    whenToUse: 'When you need to significantly reposition branches — especially for creating horizontal cloud pads or correcting lean.',
    materials: [
      'Thin wire (1mm galvanised or copper)',
      'Rubber tubing or hose sections for padding',
      'Ground stakes or anchor points',
      'Wire cutters',
    ],
    process: [
      { step: 1, description: 'Identify the branch position you want to achieve' },
      { step: 2, description: 'Cut a piece of rubber tubing slightly longer than the branch width' },
      { step: 3, description: 'Thread wire through the tubing to create a padded loop' },
      { step: 4, description: 'Wrap the padded section around the branch at the bend point' },
      { step: 5, description: 'Secure wire to ground stake, exposed root, or lower sturdy branch' },
      { step: 6, description: 'Apply gentle tension — the branch should move slightly but not crack' },
      { step: 7, description: 'Check monthly and adjust tension as the branch sets' },
    ],
    duration: '1-2 years with proper padding',
    tips: [
      'Garden trees grow too fast for bonsai-style spiral wiring',
      'Multiple anchor points allow finer control',
      'Winter application works best when sap is down',
    ],
    warnings: [
      'Check padding regularly — wire can still bite through rubber over time',
      'Never apply so much tension that bark cracks',
    ],
  },
  {
    id: 'weights',
    name: 'Weights & Props',
    description: 'Gravity-based training using suspended weights or supportive props. Slower than wiring but gentler and more natural-looking.',
    whenToUse: 'For gradual repositioning, maintaining achieved positions, or when wire scarring is a concern.',
    materials: [
      'Small cement or stone weights (0.5-2kg)',
      'Natural fibre rope or twine',
      'Bamboo poles for props',
      'Rubber padding',
    ],
    process: [
      { step: 1, description: 'For weights: Attach rope to weight, loop over branch with padding' },
      { step: 2, description: 'Start with lighter weights and increase gradually over weeks' },
      { step: 3, description: 'For props: Position bamboo pole under branch at desired angle' },
      { step: 4, description: 'Secure prop base in ground or against trunk' },
      { step: 5, description: 'Pad contact points to prevent bark damage' },
    ],
    duration: 'Ongoing — many mature niwaki have permanent props',
    tips: [
      'Weights work well for downward movement',
      'Props are essential for artificially extended horizontal branches',
      'Props become aesthetic features in traditional gardens',
    ],
    warnings: [
      'Check monthly for bark damage at contact points',
      'Remove weights during storms to prevent breakage',
    ],
  },
  {
    id: 'wiring',
    name: 'Spiral Wiring',
    description: 'Bonsai-style wiring wrapped along branches. Provides precise control but requires careful monitoring on fast-growing garden trees.',
    whenToUse: 'For fine positioning of smaller branches, detailed shaping work, or when other methods cannot achieve the desired angle.',
    materials: [
      'Anodized aluminium wire (for deciduous, thin bark)',
      'Annealed copper wire (for conifers, thick bark)',
      'Wire cutters',
      'Jin pliers (optional)',
    ],
    process: [
      { step: 1, description: 'Select wire gauge: aluminium = 1/2 to 2/3 of branch thickness; copper = 1/3 of branch thickness' },
      { step: 2, description: 'Anchor wire with at least one full wrap around the trunk before the branch' },
      { step: 3, description: 'Wrap at consistent 45-degree angles along the branch' },
      { step: 4, description: 'Avoid crossing wires or leaving gaps' },
      { step: 5, description: 'Bend branch into position slowly after wiring' },
      { step: 6, description: 'Check weekly during growing season for wire bite' },
    ],
    duration: 'Deciduous: 3-4 months MAX. Conifers: can hold longer, sometimes years.',
    tips: [
      'Wire two branches of similar size with one piece for better anchoring',
      'Apply when slightly dry — branches are more flexible',
      'Remove before it bites in, even if position is not yet set',
    ],
    warnings: [
      'NEVER use iron or steel wire on junipers — causes blackrot',
      'Japanese maples wire-bite within weeks — check constantly',
      'Scarring is permanent and takes years to fade',
    ],
  },
];

export const WIRE_COMPARISON: WireType[] = [
  {
    type: 'Anodized Aluminium',
    bestFor: 'Deciduous trees, thin bark, beginners',
    gauge: '1/2 to 2/3 of branch thickness',
    notes: 'Softer, easier to apply, less scarring risk',
  },
  {
    type: 'Annealed Copper',
    bestFor: 'Conifers, thick bark',
    gauge: '1/3 of branch thickness',
    notes: 'Stronger holding power, half the gauge needed',
  },
  {
    type: 'Iron/Steel',
    bestFor: 'NEVER USE',
    gauge: 'N/A',
    notes: 'Poisonous to junipers, causes blackrot',
  },
];

export const SPECIES_GUIDE: Species[] = [
  {
    id: 'black-pine',
    name: 'Japanese Black Pine',
    scientificName: 'Pinus thunbergii',
    difficulty: 5,
    maintenanceFrequency: 'Twice yearly (midoritsumi + momiage)',
    bestTechniques: ['midoritsumi', 'momiage', 'sukashi'],
    notes: 'Fast-growing, responds excellently to candling',
    isTraditional: true,
  },
  {
    id: 'white-pine',
    name: 'Japanese White Pine',
    scientificName: 'Pinus parviflora',
    difficulty: 4,
    maintenanceFrequency: 'Twice yearly',
    bestTechniques: ['midoritsumi', 'momiage', 'sukashi'],
    notes: 'Slower-growing, elegant refined forms',
    isTraditional: true,
  },
  {
    id: 'scots-pine',
    name: 'Scots Pine',
    scientificName: 'Pinus sylvestris',
    difficulty: 3,
    maintenanceFrequency: 'Annual summer pruning',
    bestTechniques: ['sukashi', 'pinching'],
    notes: 'Much easier than Japanese pines — regular secateurs work fine',
    isTraditional: false,
  },
  {
    id: 'yew',
    name: 'Yew',
    scientificName: 'Taxus baccata',
    difficulty: 2,
    maintenanceFrequency: '1-2 annual trims',
    bestTechniques: ['sukashi', 'pinching'],
    notes: 'Very forgiving — regenerates from old wood',
    isTraditional: false,
  },
  {
    id: 'japanese-holly',
    name: 'Japanese Holly',
    scientificName: 'Ilex crenata',
    difficulty: 2,
    maintenanceFrequency: '1-2 annual trims',
    bestTechniques: ['sukashi', 'pinching'],
    notes: 'Dense, rigid growth ideal for cloud shapes',
    isTraditional: false,
  },
  {
    id: 'box',
    name: 'Box',
    scientificName: 'Buxus sempervirens',
    difficulty: 2,
    maintenanceFrequency: 'Frequent trimming',
    bestTechniques: ['pinching', 'sukashi'],
    notes: 'Classic European choice, watch for box blight',
    isTraditional: false,
  },
  {
    id: 'podocarpus',
    name: 'Podocarpus',
    scientificName: 'Podocarpus macrophyllus',
    difficulty: 3,
    maintenanceFrequency: 'As needed',
    bestTechniques: ['sukashi', 'pinching'],
    notes: 'Works in mild climates and indoors',
    isTraditional: false,
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'bypass-secateurs',
    name: 'Bypass Secateurs',
    purpose: 'Most cutting work',
    priceRange: '£40-50',
    recommended: 'Okatsune 103',
    category: 'cutting',
  },
  {
    id: 'premium-secateurs',
    name: 'Premium Secateurs',
    purpose: 'Fine work',
    priceRange: '£80-250+',
    recommended: 'Tobisho',
    category: 'cutting',
  },
  {
    id: 'folding-saw',
    name: 'Folding Saw',
    purpose: 'Branch removal',
    priceRange: '£35',
    recommended: 'Niwaki GR 210',
    category: 'cutting',
  },
  {
    id: 'topiary-clippers',
    name: 'Topiary Clippers',
    japaneseEquivalent: 'Hakaribasami',
    purpose: 'One-handed cloud shaping',
    category: 'cutting',
  },
  {
    id: 'garden-shears',
    name: 'Garden Shears',
    japaneseEquivalent: 'Karikomi',
    purpose: 'Larger hedge work',
    priceRange: '£330',
    recommended: 'Niwaki Karikomi',
    category: 'cutting',
  },
  {
    id: 'clean-mate',
    name: 'Mini Clean Mate',
    purpose: 'Sap/resin removal',
    category: 'maintenance',
  },
  {
    id: 'camellia-oil',
    name: 'Camellia Oil',
    purpose: 'Rust prevention',
    category: 'maintenance',
  },
  {
    id: 'aluminium-wire',
    name: 'Aluminium Wire',
    purpose: 'Branch training',
    category: 'training',
  },
  {
    id: 'natural-twine',
    name: 'Natural Fiber Twine',
    purpose: 'Tying',
    category: 'training',
  },
];

export const SEASONAL_CALENDAR: SeasonalTask[] = [
  {
    month: 12,
    season: 'winter',
    tasks: [
      'Major structural pruning on deciduous trees',
      'Framework assessment (bare branches visible)',
      'Plan next season\'s work',
    ],
    avoid: ['Pruning during frost'],
  },
  {
    month: 1,
    season: 'winter',
    tasks: [
      'Continue structural work on deciduous trees',
      'Framework assessment',
      'Order tools and supplies',
    ],
    avoid: ['Pruning during frost'],
  },
  {
    month: 2,
    season: 'winter',
    tasks: [
      'Apply guy wires at winter\'s end',
      'Final structural pruning',
      'Prepare for spring growth',
    ],
    avoid: ['Pruning during frost'],
  },
  {
    month: 3,
    season: 'spring',
    tasks: [
      'Monitor for new growth',
      'Light maintenance pruning',
    ],
  },
  {
    month: 4,
    season: 'spring',
    tasks: [
      'Watch for pine candle development',
      'Begin pinching soft growth on broadleaves',
    ],
  },
  {
    month: 5,
    season: 'spring',
    tasks: ['Primary maintenance pruning begins'],
    criticalTasks: ['Midoritsumi on pines — cannot be missed!'],
  },
  {
    month: 6,
    season: 'spring',
    tasks: [
      'Continue midoritsumi if needed',
      'Evergreen pruning begins',
    ],
    criticalTasks: ['Complete midoritsumi before candles harden'],
  },
  {
    month: 7,
    season: 'summer',
    tasks: [
      'Annual cloud trimming',
      'Partial defoliation on deciduous',
      'Fast growers (privet): first of 2-3 trims',
    ],
  },
  {
    month: 8,
    season: 'summer',
    tasks: [
      'Continue maintenance trimming',
      'Second trim for fast growers',
    ],
  },
  {
    month: 9,
    season: 'autumn',
    tasks: [
      'Flowering shrubs: prune immediately after flowering',
      'Begin momiage preparation',
    ],
  },
  {
    month: 10,
    season: 'autumn',
    tasks: [
      'Begin momiage on pines',
      'Final preparations for dormancy',
    ],
  },
  {
    month: 11,
    season: 'autumn',
    tasks: [
      'Complete momiage on pines',
      'Excellent planting season for new specimens',
    ],
  },
];

export const COMMON_MISTAKES: CommonMistake[] = [
  {
    id: 'old-wood-conifers',
    category: 'critical',
    mistake: 'Cutting into old wood on conifers',
    consequence: 'They cannot regenerate from bare branches. Once needles drop from a section, no new growth will ever appear.',
    solution: 'Only prune current or recent growth. Never cut back to bare wood.',
  },
  {
    id: 'too-many-branches',
    category: 'critical',
    mistake: 'Removing too many branches at once',
    consequence: 'Branches take years or decades to regrow, if ever.',
    solution: 'Work gradually over multiple seasons. Remove no more than 1/3 of the canopy per year.',
  },
  {
    id: 'frost-pruning',
    category: 'timing',
    mistake: 'Pruning during frost or extreme heat',
    consequence: 'Stress damage and poor healing.',
    solution: 'Wait for mild, overcast days.',
  },
  {
    id: 'flowering-before-bloom',
    category: 'timing',
    mistake: 'Cutting flowering shrubs before bloom',
    consequence: 'Loss of current season\'s flowers.',
    solution: 'Prune flowering shrubs immediately after flowering.',
  },
  {
    id: 'wire-too-long',
    category: 'timing',
    mistake: 'Leaving wire on too long',
    consequence: 'Permanent bark scarring as the branch grows around the wire.',
    solution: 'Check wire monthly. Remove before it bites in.',
  },
  {
    id: 'missing-midoritsumi',
    category: 'timing',
    mistake: 'Missing the midoritsumi window on pines',
    consequence: 'Candles harden and must be cut, producing inferior results.',
    solution: 'Mark your calendar. Check pines daily in late spring.',
  },
  {
    id: 'symmetry-obsession',
    category: 'style',
    mistake: 'Obsessing over symmetry',
    consequence: 'Creates artificial-looking trees that lack natural character.',
    solution: 'Embrace asymmetry. Authentic niwaki celebrates irregularity.',
  },
  {
    id: 'dense-masses',
    category: 'style',
    mistake: 'Creating solid, dense masses',
    consequence: 'Produces "pom-pom" shapes rather than transparent clouds.',
    solution: 'Thin clouds so light passes through. You should see sky between branches.',
  },
  {
    id: 'forcing-shapes',
    category: 'style',
    mistake: 'Forcing shapes onto trees',
    consequence: 'Constant fighting against natural growth. Higher maintenance, less beauty.',
    solution: 'Work WITH natural tendencies, not against them.',
  },
  {
    id: 'abandonment',
    category: 'maintenance',
    mistake: 'Abandoning purchased specimens',
    consequence: 'Shapes deteriorate within 2-3 years without consistent maintenance.',
    solution: 'Commit to regular maintenance before purchasing. Budget time as well as money.',
  },
  {
    id: 'over-fertilising',
    category: 'maintenance',
    mistake: 'Over-fertilising',
    consequence: 'Heavy nitrogen promotes rapid, unattractive growth.',
    solution: 'Keep feeding gentle. Less is more.',
  },
];

export const YEAR_ONE_PLAN: YearOnePlan[] = [
  {
    phase: 'Assessment',
    months: '1-2',
    tasks: [
      'Study the tree\'s existing structure',
      'Identify strongest and weakest areas',
      'Sketch intended design',
      'Remove obvious dead wood only',
    ],
  },
  {
    phase: 'Initial Thinning',
    months: '3-4',
    tasks: [
      'Apply Rule of Two at major forks',
      'Remove crossing/inward branches',
      'Establish basic cloud pad locations',
    ],
  },
  {
    phase: 'Training',
    months: '5-8',
    tasks: [
      'Install guy wires for horizontal branches',
      'Begin regular pinching on appropriate species',
      'Perform species-specific seasonal tasks',
    ],
  },
  {
    phase: 'Refinement',
    months: '9-12',
    tasks: [
      'Fine-tune cloud shapes',
      'Complete autumn needle work (pines)',
      'Document progress with photographs',
      'Plan Year Two developments',
    ],
  },
];

export const RESOURCES: Resources = {
  books: [
    {
      title: 'Niwaki: Pruning, Training and Shaping Trees the Japanese Way',
      author: 'Jake Hobson',
    },
    {
      title: 'The Art of Japanese Gardens',
      author: 'Günter Nitschke',
    },
    {
      title: 'Japanese Garden Design',
      author: 'Marc Peter Keane',
    },
  ],
  suppliers: [
    { name: 'Niwaki Ltd (UK)', url: 'niwaki.com' },
    { name: 'Okatsune (Japan)', url: undefined },
    { name: 'Tobisho (Japan)', url: undefined },
  ],
  gardens: [
    'Katsura Imperial Villa, Kyoto',
    'Portland Japanese Garden, Oregon',
    'Japanese Garden, The Hague',
    'RHS Garden Wisley, Surrey',
  ],
};
